name: Clang Format

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Clang Format
      uses: lukka/clang-format-action@v2
      with:
        clang-format-path: /usr/bin/clang-format
        commit: true