name: Style Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  style-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up clang-format
      run: sudo apt-get install -y clang-format

    - name: Get list of changed files
      id: changed-files
      run: |
        echo "::set-output name=files::$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E '\.(cpp|h)$')"

    - name: Check code style
      run: |
        if [ -n "${{ steps.changed-files.outputs.files }}" ]; then
          echo "${{ steps.changed-files.outputs.files }}" | xargs clang-format -i --style=Google
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          if ! git diff --quiet; then
            git checkout -b style-fixes
            git add .
            git commit -m "Apply clang-format fixes"
            git push origin style-fixes
          fi
        else
          echo "No C++ files changed."
        fi

    - name: Create pull request with style fixes
      if: success() && steps.changed-files.outputs.files != ''
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: style-fixes
        title: 'Style fixes'
        body: 'This PR applies clang-format style fixes according to Google style guide.'
        base: ${{ github.event.pull_request.head.ref }}
        labels: 'auto-generated'

    - name: Post PR comment
      if: success() && steps.changed-files.outputs.files != ''
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Proposed style fixes are available in a separate pull request. Please review and merge if acceptable.'
          })